(()=>{
 const page=document.getElementById('weiyuan-detail');if(!page)return;
 const year=page.querySelector('.wy-year-watermark');
 page.addEventListener('scroll',()=>{const y=page.scrollTop,v=innerHeight,enter=Math.max(0,Math.min(1,(y-v*.28)/(v*.6))),fade=Math.max(0,Math.min(1,(page.scrollHeight-y-v)/(v*.8)));year.style.opacity=String(enter*fade);year.style.transform='translate(-50%,'+(-42+y*.008)+'%) scale('+(0.9+enter*.12)+')'}, {passive:true});
 const baseOpen=window.openProject,lightbox=page.querySelector('.wy-lightbox'),hunger=page.querySelector('.wy-hunger-dialog');
 const cover=page.querySelector('.wy-video-cover'),videoShell=page.querySelector('.wy-video-shell'),reset=page.querySelector('[data-wy-video-reset]');
 let returnFocus,previewFocus,previousOverflow='',storyIndex=0;
 const thumbs=[...page.querySelectorAll('[data-story-index]')],storyMain=page.querySelector('.wy-story-main');
 function selectStory(i){storyIndex=(i+thumbs.length)%thumbs.length;const thumb=thumbs[storyIndex],src=thumb.querySelector('img').getAttribute('src'),title=thumb.dataset.title;storyMain.querySelector('img').src=src;storyMain.querySelector('img').alt=title;page.querySelector('#wy-story-count').textContent=String(storyIndex+1).padStart(2,'0')+' / 13';page.querySelector('#wy-story-title').textContent=title;thumbs.forEach((b,j)=>b.setAttribute('aria-pressed',j===storyIndex));const rail=thumb.parentElement;rail.scrollTo({left:thumb.offsetLeft-rail.offsetLeft-rail.clientWidth/2+thumb.clientWidth/2,behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'instant':'smooth'})}
 function resetVideo(){videoShell.querySelector('iframe')?.remove();cover.hidden=false;reset.hidden=true}
 function closePreview(){lightbox.hidden=true;previewFocus?.focus({preventScroll:true})}
 function close(){if(page.hidden)return;if(hunger.open)hunger.close();resetVideo();lightbox.hidden=true;page.hidden=true;document.body.classList.remove('is-weiyuan-open','is-project-open');document.body.style.overflow=previousOverflow;returnFocus?.focus({preventScroll:true})}
 window.closeWeiyuanProject=close;
 window.openProject=function(id){if(id!=='weiyuan'){if(!page.hidden)close();return baseOpen?.apply(this,arguments)}if(!page.hidden)return;returnFocus=document.activeElement;previousOverflow=document.body.style.overflow;page.hidden=false;window.dispatchEvent(new Event('weiyuan-open'));year.style.opacity=0;page.scrollTo({top:0,behavior:'instant'});document.body.style.overflow='hidden';document.body.classList.add('is-project-open','is-weiyuan-open');resetVideo();selectStory(Math.floor(Math.random()*thumbs.length));page.querySelector('[data-wy-close]').focus({preventScroll:true})};
 page.querySelectorAll('[data-wy-close]').forEach(b=>b.onclick=close);
 page.querySelectorAll('a[href^="#wy-"]').forEach(a=>a.onclick=e=>{e.preventDefault();page.querySelector(a.getAttribute('href'))?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'instant':'smooth'})});
 document.querySelectorAll('[data-wy-hunger]').forEach(b=>{b.title='点击了解隐性饥饿';b.addEventListener('click',e=>{e.stopPropagation();if(page.hidden)window.openProject('weiyuan');hunger.showModal();const cursor=document.querySelector('.target-cursor-wrapper');if(cursor)hunger.appendChild(cursor);window.refreshTargetCursor?.()})});
 hunger.addEventListener('close',()=>{const cursor=hunger.querySelector('.target-cursor-wrapper');if(cursor)document.body.appendChild(cursor);window.refreshTargetCursor?.()});
 hunger.querySelector('.wy-hunger-close').onclick=()=>hunger.close();hunger.addEventListener('click',e=>{if(e.target===hunger){const r=hunger.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)hunger.close()}});
 page.addEventListener('click',e=>{const b=e.target.closest('[data-wy-image]');if(!b)return;previewFocus=b;lightbox.querySelector('img').src=b.dataset.wyImage;lightbox.querySelector('img').alt=b.dataset.caption;lightbox.querySelector('p').textContent=b.dataset.caption;lightbox.hidden=false;lightbox.querySelector('button').focus()});
 lightbox.addEventListener('click',e=>{if(e.target===lightbox||e.target.closest('button'))closePreview()});
 thumbs.forEach((b,i)=>b.onclick=()=>selectStory(i));page.querySelector('[data-story-prev]').onclick=()=>selectStory(storyIndex-1);page.querySelector('[data-story-next]').onclick=()=>selectStory(storyIndex+1);
 cover.onclick=()=>{const frame=document.createElement('iframe');frame.title='微元灵溯——基于Unity的维生素交互科普游戏';frame.allow='autoplay; fullscreen; picture-in-picture';frame.allowFullscreen=true;frame.referrerPolicy='strict-origin-when-cross-origin';frame.src='https://player.bilibili.com/player.html?bvid=BV1DC8geEE1f&page=1&autoplay=1&danmaku=0';cover.hidden=true;reset.hidden=false;videoShell.appendChild(frame)};reset.onclick=resetVideo;
 document.addEventListener('keydown',e=>{if(page.hidden||hunger.open)return;if(e.key==='Escape'){e.preventDefault();if(!lightbox.hidden)closePreview();else close()}if(e.key==='Tab'){const scope=lightbox.hidden?page:lightbox;const list=[...scope.querySelectorAll('button,a[href],[tabindex="0"]')].filter(el=>el.getClientRects().length&&el.tabIndex>=0);const first=list[0],last=list.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}});
})();

(()=>{
 const page=document.getElementById('weiyuan-detail');if(!page)return;
 const reduced=matchMedia('(prefers-reduced-motion: reduce)'),played=new WeakSet(),running=new Set();
 const enter=new IntersectionObserver(entries=>entries.forEach(({target,isIntersecting})=>{if(!isIntersecting||page.hidden||played.has(target))return;played.add(target);if(reduced.matches)return;const animation=target.animate([{opacity:0,transform:'translateY(20px)'},{opacity:1,transform:'translateY(0)'}],{duration:650,easing:'cubic-bezier(.22,1,.36,1)'});running.add(animation);animation.onfinish=()=>running.delete(animation)}),{root:page,threshold:.12});
 page.querySelectorAll('.wy-hero-art,.wy-meta,.wy-hero-copy>.wy-pill,.wy-picture,.wy-stage-list,.wy-story-main,.wy-story-thumbs,.wy-story-controls,.wy-flow-details,.wy-video-shell,.wy-video-links,.wy-footer>.wy-pill').forEach(el=>enter.observe(el));
 const watchAdded=new MutationObserver(()=>page.querySelectorAll('.ag-panel__frame,.wy-inline-assets button,.wy-magnet-item').forEach(el=>{if(!el.dataset.wyEntrance){el.dataset.wyEntrance='1';enter.observe(el)}}));watchAdded.observe(page,{childList:true,subtree:true});
 const ambient=new IntersectionObserver(entries=>entries.forEach(({target,isIntersecting})=>target.classList.toggle('wy-motion-awake',isIntersecting)),{root:page,threshold:.02});
 page.querySelectorAll('.wy-hero,#wy-accordion-root').forEach(el=>ambient.observe(el));
 function pause(){page.classList.toggle('wy-motion-paused',document.hidden||page.hidden)}
 new MutationObserver(pause).observe(page,{attributes:true,attributeFilter:['hidden']});document.addEventListener('visibilitychange',pause);pause();
 reduced.addEventListener('change',()=>{if(reduced.matches){running.forEach(a=>a.cancel());running.clear()}});
})();

(()=>{const page=document.getElementById('weiyuan-detail'),logo=page?.querySelector('.wy-hero-emblem');if(!logo)return;const mq=matchMedia('(prefers-reduced-motion: reduce), (pointer: coarse)');let raf=0,x=0,y=0;const reset=()=>{x=y=0;logo.style.translate='0px 0px'};logo.style.transition='translate .28s ease-out';function move(e){if(page.hidden||document.hidden||mq.matches){reset();return}const r=logo.parentElement.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+logo.offsetTop+logo.clientHeight/2;const dx=e.clientX-cx,dy=e.clientY-cy;if(Math.abs(dx)<logo.clientWidth/2+90&&Math.abs(dy)<logo.clientHeight/2+90){x=Math.max(-48,Math.min(48,dx/3));y=Math.max(-40,Math.min(40,dy/3))}else{x=y=0}if(!raf)raf=requestAnimationFrame(()=>{raf=0;logo.style.translate=x+'px '+y+'px'})}window.addEventListener('mousemove',move,{passive:true});window.addEventListener('blur',reset);document.addEventListener('mouseleave',reset);document.addEventListener('visibilitychange',reset);mq.addEventListener('change',reset);new MutationObserver(()=>{if(page.hidden)reset()}).observe(page,{attributes:true,attributeFilter:['hidden']})})();
